export const ERROR_CODES = {
  generic: {
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',
  },

  user: {
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  },

  auth: {
    INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
    ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
    ACCOUNT_SUSPENDED: 'ACCOUNT_SUSPENDED',
    EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
    PASSWORD_RESET_REQUIRED: 'PASSWORD_RESET_REQUIRED',
    WEAK_PASSWORD: 'WEAK_PASSWORD',
    UNAUTHORIZED: 'UNAUTHORIZED',
  },

  token: {
    TOKEN_NOT_FOUND: 'TOKEN_NOT_FOUND',
    TOKEN_EXPIRED: 'TOKEN_EXPIRED',
    TOKEN_ALREADY_USED: 'TOKEN_ALREADY_USED',
  },

  oauth: {
    OAUTH_ACCOUNT_NOT_FOUND: 'OAUTH_ACCOUNT_NOT_FOUND',
    OAUTH_ACCOUNT_ALREADY_LINKED: 'OAUTH_ACCOUNT_ALREADY_LINKED',
  },

  session: {
    SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',
    SESSION_EXPIRED: 'SESSION_EXPIRED',
    SESSION_INVALID: 'SESSION_INVALID',
  },

  workspace: {
    WORKSPACE_NOT_FOUND: 'WORKSPACE_NOT_FOUND',
    WORKSPACE_MEMBER_NOT_FOUND: 'WORKSPACE_MEMBER_NOT_FOUND',
    NOT_WORKSPACE_MEMBER: 'NOT_WORKSPACE_MEMBER',
    INSUFFICIENT_PERMISSIONS: 'INSUFFICIENT_PERMISSIONS',
    SOLE_OWNER: 'SOLE_OWNER',
    ADMIN_CANNOT_ASSIGN_OWNER: 'ADMIN_CANNOT_ASSIGN_OWNER',
    ADMIN_CANNOT_REMOVE_PRIVILEGED: 'ADMIN_CANNOT_REMOVE_PRIVILEGED',
    WORKSPACE_MEMBER_ALREADY_EXISTS: 'WORKSPACE_MEMBER_ALREADY_EXISTS',
    SOLE_OWNER_BLOCKS_DELETION: 'SOLE_OWNER_BLOCKS_DELETION',
  },

  invite: {
    INVITE_NOT_FOUND: 'INVITE_NOT_FOUND',
    INVITE_ALREADY_EXISTS: 'INVITE_ALREADY_EXISTS',
    INVITE_EXPIRED: 'INVITE_EXPIRED',
  },

  vehicle: {
    VEHICLE_NOT_FOUND: 'VEHICLE_NOT_FOUND',
  },

  media: {
    MEDIA_NOT_FOUND: 'MEDIA_NOT_FOUND',
    MEDIA_OWNERSHIP: 'MEDIA_OWNERSHIP',
    INVALID_FILE_TYPE: 'INVALID_FILE_TYPE',
    FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  },

  timeline: {
    TIMELINE_EVENT_NOT_FOUND: 'TIMELINE_EVENT_NOT_FOUND',
  },

  tire: {
    TIRE_NOT_FOUND: 'TIRE_NOT_FOUND',
    TIRE_CHANGE_NOT_FOUND: 'TIRE_CHANGE_NOT_FOUND',
  },
} as const;
